name: home

on:
  push:
    paths:
      - "home.js"
  schedule:
    - cron: "* * * * *"

jobs:
  home:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm i
      - run: node home.js
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add '*-home.json' -f
          git commit -m "Update data"
          git fetch --all
          git checkout gh-pages
          git checkout main '*-home.json'
          git add '*.json' -f
          git commit --amend -m "Update data"
          git push --force
